# Copyright (c) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

[package]
name = "kata-ctl"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "cargo"] }
serde_json.workspace = true
thiserror.workspace = true
privdrop.workspace = true
nix.workspace = true
strum.workspace = true
strum_macros.workspace = true
serde.workspace = true
url.workspace = true
futures.workspace = true
base64.workspace = true
toml.workspace = true
sys-info.workspace = true

shim-interface.workspace = true
kata-types.workspace = true
kata-sys-util.workspace = true
kata-hypervisor.workspace = true
agent.workspace = true
virt_container.workspace = true
common.workspace = true
serial_test.workspace = true
vmm-sys-util.workspace = true
epoll.workspace = true
libc.workspace = true

# Note: this crate sets the slog 'max_*' features which allows the log level
# to be modified at runtime.
logging.workspace = true
slog.workspace = true
slog-scope.workspace = true
hyper.workspace = true
tokio = { workspace = true, features = ["signal"] }

prometheus.workspace = true
procfs.workspace = true
lazy_static.workspace = true

# for log-parser
serde_yaml.workspace = true
ron.workspace = true
quick-xml.workspace = true
csv.workspace = true
serde_with.workspace = true
chrono.workspace = true
rstest.workspace = true

[target.'cfg(target_arch = "s390x")'.dependencies]
reqwest = { workspace = true, features = ["native-tls"] }

[target.'cfg(not(target_arch = "s390x"))'.dependencies]
reqwest.workspace = true

[dev-dependencies]
semver.workspace = true
tempfile.workspace = true
nix.workspace = true
test-utils.workspace = true
micro_http.workspace = true

[package.metadata.cargo-machete]
ignored = ["strum"]
